export enum TwilioActionTypes {
  SET_TWILIO_TOKEN = "SET_TWILIO_TOKEN",
  SET_IDENTITY = "SET_IDENTITY",
  SET_IS_CONNECTED = "SET_IS_CONNECTED",
  ADD_PARTICIPANT = "ADD_PARTICIPANT",
  REMOVE_PARTICIPANT = "REMOVE_PARTICIPANT"
}